[package]
name = "cairo_lib"
version = "0.2.0"
edition = "2024_07"
description = "A library for Cairo"
homepage = "https://github.com/HerodotusDev/cairo-lib"

[dependencies]
starknet = "2.12.0"

[dev-dependencies]
snforge_std = "0.48.0"
assert_macros = "2.12.0"

[scripts]
test = "snforge test"
